import Head from 'next/head'
import Image from 'next/image' 


// graphql imports
import gql from 'graphql-tag' 
import { Query } from 'react-apollo'
import withData from '../config';

export default function Home() {
  const query = gql`
   query {
    MyJobsToDO {
     id
     JobTitle
     Description
    }
   }
`
  return (
    < >
      <Head>
        <title>Hasura      App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <Query query={ query } fetchPolicy={ 'cache-and-network' }>
      {({ loading, data: { MyJobToDO:MyJobsToDO }}) => {
        return (
          <div>
            <div>
             {MyJobsToDO.map((a, i) => (
                <div key={i}>
                 <h2>{a.JobTitle}</h2>
                 <p>{a.Description}</p>
                </div>
             ))}
            </div>
          </div>
        );
      }}
  </Query>
      
    </ >
  )
}
