import Head from 'next/head'
import Image from 'next/image' 


// graphql imports
import gql from 'graphql-tag' 
import { Query } from 'react-apollo'
import withData from '../config';

export default function Home() {
  const query = gql`
   query {
    author {
     id
     name
    }
   }
`
  return (
    < >
      <Head>
        <title>Hasura      App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <Query query={ query } fetchPolicy={ 'cache-and-network' }>
      {({ loading, data: { author:authors }}) => {
        return (
          <div>
            <div>
             {authors.map((a, i) => (
                <div key={i}>
                 <h2>{a.name}</h2>
                </div>
             ))}
            </div>
          </div>
        );
      }}
  </Query>
      
    </ >
  )
}
